export const muiApi = {
  "mui-media-player": {
    description:
      "Renders native or embedded audio and video media from a supplied source, with optional Muibook controls for direct media files and composable metadata for titles, avatars, links, badges, and product actions.",
    attributes: [
      { name: "src", type: { text: "string" }, description: "Media URL to render." },
      { name: "type", type: { text: '"video" | "audio" | "youtube" | "soundcloud"' }, description: "Overrides media type detection for the source URL." },
      { name: "controls", type: { text: '"player" | "none"' }, default: "player", description: "Chooses whether Muibook controls are rendered over the native media element." },
      { name: "poster", type: { text: "string" }, description: "Poster image URL for native video media." },
      { name: "artwork", type: { text: "string" }, description: "Optional artwork image URL for audio artwork presentation." },
      { name: "media-title", type: { text: "string" }, description: "Fallback title displayed in audio presentations or video metadata when slot='meta-before' is not provided." },
      { name: "height", type: { text: "string" }, description: "Sets the audio metadata or artwork presentation height using any valid CSS height value. Maps to --media-player-audio-height." },
      { name: "waveform", type: { text: "boolean" }, default: "false", description: "Opt-in generated waveform for audio presentations. The component fetches and decodes the source when possible; remote sources may not render a waveform if CORS blocks decoding." },
      { name: "center-play", type: { text: "boolean" }, default: "false", description: "Displays an always-visible centered play/pause action over native video." },
      { name: "loading", type: { text: "boolean" }, default: "false", description: "Forces the centered loading affordance for externally managed loading states, demos, or diagnostics." },
      { name: "autoplay", type: { text: "boolean" }, default: "false", description: "Opt-in setting that requests automatic playback when allowed by the browser. Avoid enabling by default unless the experience clearly requires it." },
      { name: "muted", type: { text: "boolean" }, default: "false", description: "Starts native media muted." },
      { name: "loop", type: { text: "boolean" }, default: "false", description: "Restarts playback when media ends." },
    ],
    slots: [
      { name: "meta-before", description: "Optional composed top-left metadata content for audio presentations and video metadata. Use it for avatar, title, supporting copy, links, or badges. Overrides the media-title fallback layout." },
      { name: "meta-after", description: "Optional composed top-right metadata content for actions, links, badges, or supporting controls. The space between meta-before and meta-after remains available for media playback interaction." },
    ],
    cssProperties: [
      { name: "--media-player-main-radius", description: "Responsive radius used by the main media player frame and visual surfaces." },
      { name: "--media-player-audio-height", description: "Preferred height used for audio metadata and artwork presentations." },
      { name: "--media-player-seek-color", description: "Color used for the custom seek control." },
      { name: "--media-player-range-color", description: "Theme-aware color used for the active range track." },
      { name: "--media-player-range-thumb-color", description: "Theme-aware color used for the range thumb." },
      { name: "--media-player-range-track-color", description: "Theme-aware color used for the inactive range track." },
      { name: "--media-player-range-preview-color", description: "Theme-aware color used for the seek hover preview segment." },
      { name: "--media-player-waveform-color", description: "Theme-aware color used for the primary generated audio waveform bars." },
      { name: "--media-player-waveform-mirror-color", description: "Theme-aware color used for the mirrored generated audio waveform bars." },
      { name: "--media-player-waveform-active-color", description: "Theme-aware color used for generated audio waveform bars before the current playback position." },
      { name: "--media-player-waveform-active-mirror-color", description: "Theme-aware color used for mirrored generated audio waveform bars before the current playback position." },
      { name: "--media-player-control-background", description: "Theme-aware background used by compact audio controls." },
      { name: "--media-player-control-color", description: "Theme-aware text and icon color used by compact audio controls." },
      { name: "--media-player-center-action-background", description: "Theme-aware background used by centered media actions on no-image surfaces." },
      { name: "--media-player-center-action-overlay-background", description: "Locked dark background used by centered media actions over video or artwork." },
      { name: "--media-player-center-action-overlay-background-hover", description: "Locked dark hover background used by centered media actions over video or artwork." },
      { name: "--media-player-controls-peek-background", description: "Theme-aware background used by the hidden-controls peek indicator." },
      { name: "--media-player-controls-peek-shadow", description: "Theme-aware shadow used by the hidden-controls peek indicator." },
      { name: "--media-player-audio-controls-peek-background", description: "Theme-aware background used by the hidden-controls peek indicator on no-image audio surfaces." },
      { name: "--media-player-audio-controls-peek-shadow", description: "Theme-aware shadow used by the hidden-controls peek indicator on no-image audio surfaces." },
      { name: "--media-player-frame-shadow", description: "Theme-aware shadow used by audio metadata and artwork frames." },
      { name: "--media-player-video-shadow", description: "Locked overlay shadow used by video media shells." },
      { name: "--media-player-artwork-shadow", description: "Theme-aware shadow used by standalone audio artwork images before full-bleed artwork mode." },
      { name: "--media-player-thumbnail-shadow", description: "Theme-aware shadow used by metadata avatars and fallback images." },
      { name: "--media-player-dark-thumbnail-border", description: "Locked dark border used by metadata avatars and fallback images over artwork or video." },
      { name: "--media-player-dark-thumbnail-shadow", description: "Locked dark shadow used by metadata avatars and fallback images over artwork or video." },
      { name: "--media-player-meta-icon-shadow", description: "Theme-aware shadow used by audio metadata fallback icons." },
      { name: "--media-player-range-thumb-shadow", description: "Theme-aware shadow used by seek and volume range thumbs." },
      { name: "--media-player-meta-text-shadow", description: "Theme-aware text shadow used by metadata over artwork." },
      { name: "--media-player-surface-overlay-start", description: "Theme-aware top overlay color for audio metadata surfaces." },
      { name: "--media-player-surface-overlay-end", description: "Theme-aware bottom overlay color for audio metadata controls." },
      { name: "--media-player-dark-background", description: "Locked dark background used by video and artwork-backed audio." },
      { name: "--media-player-dark-control-color", description: "Locked dark-surface text and icon color used by overlay controls." },
      { name: "--media-player-dark-range-color", description: "Locked dark-surface active range track color." },
      { name: "--media-player-dark-range-thumb-color", description: "Locked dark-surface range thumb color." },
      { name: "--media-player-dark-range-track-color", description: "Locked dark-surface inactive range track color." },
      { name: "--media-player-dark-range-thumb-shadow", description: "Locked dark-surface shadow used by seek and volume range thumbs." },
      { name: "--media-player-dark-control-background-hover", description: "Locked dark-surface hover background for tertiary controls." },
      { name: "--media-player-dark-overlay-background", description: "Locked dark overlay gradient color used by video and artwork-backed audio." },
      { name: "--media-player-dark-overlay-controls-background", description: "Locked dark overlay gradient color used by video and artwork controls." },
    ],
  },
};
