export const muiApi = {
  "mui-media-player": {
    description: "Renders native or embedded audio and video media from a supplied source, with optional Muibook controls for direct media files.",
    attributes: [
      { name: "src", type: { text: "string" }, description: "Media URL to render." },
      { name: "type", type: { text: '"video" | "audio" | "youtube" | "soundcloud"' }, description: "Overrides media type detection for the source URL." },
      { name: "controls", type: { text: '"player" | "thumbnail" | "none"' }, default: "player", description: "Chooses the controls presentation for direct audio/video. Player renders Muibook controls over the native media element; thumbnail opts audio into the richer thumbnail presentation." },
      { name: "poster", type: { text: "string" }, description: "Poster image URL for native video media." },
      { name: "thumbnail", type: { text: "string" }, description: "Optional thumbnail image URL for audio thumbnail presentation." },
      { name: "artwork", type: { text: "string" }, description: "Optional artwork image URL for audio artwork presentation." },
      { name: "media-title", type: { text: "string" }, description: "Required title for the audio metadata presentation." },
      { name: "autoplay", type: { text: "boolean" }, default: "false", description: "Starts playback automatically when allowed by the browser." },
      { name: "muted", type: { text: "boolean" }, default: "false", description: "Starts native media muted." },
      { name: "loop", type: { text: "boolean" }, default: "false", description: "Restarts playback when media ends." },
    ],
    slots: [
      { name: "meta", description: "Optional supporting metadata displayed under the required media-title in audio metadata, thumbnail, and artwork presentations." },
    ],
    cssProperties: [
      { name: "--media-player-audio-height", description: "Minimum height used for audio metadata, thumbnail, and artwork presentations." },
      { name: "--media-player-video-ratio", description: "Aspect ratio used for video media." },
      { name: "--media-player-soundcloud-ratio", description: "Aspect ratio used for SoundCloud media." },
      { name: "--media-player-seek-color", description: "Color used for the custom seek control." },
      { name: "--media-player-range-color", description: "Theme-aware color used for the active range track." },
      { name: "--media-player-range-thumb-color", description: "Theme-aware color used for the range thumb." },
      { name: "--media-player-range-track-color", description: "Theme-aware color used for the inactive range track." },
      { name: "--media-player-control-background", description: "Theme-aware background used by compact audio controls." },
      { name: "--media-player-control-color", description: "Theme-aware text and icon color used by compact audio controls." },
      { name: "--media-player-center-play-background", description: "Theme-aware background used by the centered play action in surface presentations." },
      { name: "--media-player-controls-peek-background", description: "Theme-aware background used by the hidden-controls peek indicator." },
      { name: "--media-player-controls-peek-shadow", description: "Theme-aware shadow used by the hidden-controls peek indicator." },
      { name: "--media-player-audio-controls-peek-background", description: "Theme-aware background used by the hidden-controls peek indicator on no-image audio surfaces." },
      { name: "--media-player-audio-controls-peek-shadow", description: "Theme-aware shadow used by the hidden-controls peek indicator on no-image audio surfaces." },
      { name: "--media-player-shadow-thin", description: "Thin theme-aware media player shadow." },
      { name: "--media-player-shadow-medium", description: "Medium theme-aware media player shadow." },
      { name: "--media-player-shadow-thick", description: "Thick theme-aware media player shadow." },
      { name: "--media-player-frame-shadow", description: "Theme-aware shadow used by audio metadata and thumbnail frames." },
      { name: "--media-player-video-shadow", description: "Locked overlay shadow used by video media shells." },
      { name: "--media-player-artwork-shadow", description: "Theme-aware shadow used by standalone audio artwork thumbnails before full-bleed artwork mode." },
      { name: "--media-player-thumbnail-shadow", description: "Theme-aware shadow used by audio metadata thumbnail images." },
      { name: "--media-player-dark-thumbnail-border", description: "Locked dark border used by audio metadata thumbnail images over artwork." },
      { name: "--media-player-dark-thumbnail-shadow", description: "Locked dark shadow used by audio metadata thumbnail images over artwork." },
      { name: "--media-player-meta-icon-shadow", description: "Theme-aware shadow used by audio metadata fallback icons." },
      { name: "--media-player-range-thumb-shadow", description: "Theme-aware shadow used by seek and volume range thumbs." },
      { name: "--media-player-meta-text-shadow", description: "Theme-aware text shadow used by metadata over artwork." },
      { name: "--media-player-surface-overlay-start", description: "Theme-aware top overlay color for audio metadata surfaces." },
      { name: "--media-player-surface-overlay-end", description: "Theme-aware bottom overlay color for audio metadata controls." },
      { name: "--media-player-dark-background", description: "Locked dark background used by video and thumbnail-backed audio." },
      { name: "--media-player-dark-control-color", description: "Locked dark-surface text and icon color used by overlay controls." },
      { name: "--media-player-dark-range-color", description: "Locked dark-surface active range track color." },
      { name: "--media-player-dark-range-thumb-color", description: "Locked dark-surface range thumb color." },
      { name: "--media-player-dark-range-track-color", description: "Locked dark-surface inactive range track color." },
      { name: "--media-player-dark-control-background-hover", description: "Locked dark-surface hover background for tertiary controls." },
      { name: "--media-player-dark-overlay-background", description: "Locked dark overlay gradient color used by video and thumbnail-backed audio." },
    ],
  },
};
