export const muiKeywords: Record<string, string[]> = {
  alert: ["alert", "success", "info", "warning", "error", "message", "banner", "notification"],
  message: ["message", "notice", "notification", "alert", "info", "positive", "neutral", "warning", "attention"],
  badge: ["badge", "label", "tag", "notification"],
  button: ["button", "click", "action", "submit", "cta", "primary", "secondary", "tertiary", "attention"],
  "button-group": ["button group", "buttons", "actions", "group", "right", "align"],
  icon: ["icon", "glyph", "symbol", "add", "plus"],
  link: ["link", "anchor", "hyperlink", "navigation", "primary", "secondary", "tertiary", "attention"],
  tab: ["tab", "tab bar", "tab controller", "tab panel", "navigation", "tabs"],
  carousel: ["carousel", "slider", "carousel controller", "carousel panel", "carousel item", "carousel tabs"],
  card: ["card", "panel", "box", "tile"],
  stack: ["stack", "v-stack", "h-stack", "vertical", "horizontal", "spacing"],
  grid: ["grid", "columns", "rows", "layout", "container"],
  container: ["container", "wrapper", "layout", "section"],
  responsive: ["responsive", "breakpoint", "mobile", "desktop", "showAbove", "showBelow"],
  rule: ["rule", "divider", "separator", "line", "hr"],
  heading: ["heading", "title", "h1", "h2", "h3", "level"],
  body: ["body", "text", "paragraph", "copy"],
  list: ["list", "items", "ul", "li"],
};
