export const muiApi = {
  "mui-input": {
    description: "Captures a single text-like form value with label, validation state and composable affordance slots.",
    members: [{ kind: "field", name: "value", type: { text: "string" }, description: "Gets or sets the current input value." }],
    attributes: [
      {
        name: "type",
        type: { text: '"text" | "password" | "email" | "number" | "search" | "tel" | "url" | "date" | "time" | "datetime-local" | "month" | "week"' },
        default: "text",
        description: "Native input data type.",
      },
      { name: "name", type: { text: "string" }, description: "Form field name." },
      { name: "value", type: { text: "string" }, default: "", description: "Current input value." },
      { name: "placeholder", type: { text: "string" }, description: "Hint displayed when no value is entered." },
      { name: "id", type: { text: "string" }, description: "Input identifier used to associate the visible label." },
      { name: "label", type: { text: "string" }, description: "Accessible input label. Required for labelled form usage." },
      {
        name: "description",
        type: { text: "string" },
        description: "Persistent supporting text displayed between the label and control and associated with the native input.",
      },
      {
        name: "disabled",
        type: { text: "boolean" },
        default: "false",
        description: "Disables input interaction.",
      },
      {
        name: "hide-label",
        type: { text: "boolean" },
        default: "false",
        description: "Visually hides the supplied label while preserving it as the accessible name.",
      },
      {
        name: "variant",
        type: { text: '"default" | "success" | "warning" | "error"' },
        default: "default",
        description: "Visual validation state.",
      },
      {
        name: "optional",
        type: { text: "boolean" },
        default: "false",
        description: "Displays an optional marker beside the label.",
      },
      {
        name: "max-length",
        type: { text: "number | string" },
        description: "Maximum character length. Providing it displays a live count.",
      },
      {
        name: "size",
        type: { text: '"x-small" | "small" | "medium" | "large"' },
        default: "medium",
        description: "Input and slotted affordance size scale.",
      },
      {
        name: "align",
        type: { text: '"start" | "center" | "end"' },
        default: "start",
        description: "Text alignment inside the input. Use 'end' for quantitative values like amounts, rates, balances, and quantities.",
      },
      {
        name: "input-mode",
        type: { text: '"decimal" | "numeric" | "text" | "email" | "url" | "search" | "tel" | "none"' },
        description: "Virtual keyboard hint for mobile/touch devices. Use 'decimal' for monetary amounts and quantities.",
      },
      {
        name: "pattern",
        type: { text: "string" },
        description: "Regex pattern for native input value validation.",
      },
      {
        name: "step",
        type: { text: "string | number" },
        description: "Granularity/step constraint for numeric or decimal input values.",
      },
      {
        name: "slot-layout",
        type: { text: '"inline" | "stack-mobile"' },
        default: "inline",
        description: "Arranges external before and after slots inline or stacked around the input.",
      },
      {
        name: "surface",
        type: { text: '"default" | "seamless"' },
        default: "default",
        description: "Visual surface style. Seamless removes borders and backgrounds.",
      },
      {
        name: "autofocus",
        type: { text: "boolean" },
        default: "false",
        description: "Focuses the input after it renders.",
      },
      { name: "padding-block", type: { text: "string" }, description: "Overrides native input block padding with a CSS length or token." },
      { name: "padding-inline", type: { text: "string" }, description: "Overrides native input inline padding with a CSS length or token." },
    ],
    slots: [
      {
        name: "description",
        description: "Rich supporting content displayed between the label and control. Prefer `mui-body`; it replaces the description attribute fallback.",
      },
      { name: "before", description: "Flush leading control, such as `mui-addon`, `mui-select`, `mui-button` or `mui-chip`." },
      { name: "after", description: "Flush trailing control, such as `mui-addon`, `mui-select`, `mui-button` or `mui-chip`." },
      { name: "inside-before", description: "Leading content displayed inside the input edge, such as an icon, badge, or prefix text. Alias: `inside-start`." },
      { name: "inside-start", description: "Leading content displayed inside the input edge, such as an icon, badge, or prefix text (e.g. currency symbol)." },
      { name: "inside-after", description: "Trailing content displayed inside the input edge, such as an icon, badge, or suffix text. Alias: `inside-end`." },
      { name: "inside-end", description: "Trailing content displayed inside the input edge, such as an icon, badge, or suffix text (e.g. currency code)." },
      { name: "hint", description: "Contextual hint content displayed inside the trailing input affordance area." },
    ],
    events: [
      { name: "input", description: "Composed, bubbling event dispatched during value entry with `detail.value`." },
      { name: "change", description: "Composed, bubbling event dispatched when the native input change event occurs with `detail.value`." },
    ],
    methods: [{ name: "focus", description: "Moves focus to the internal native input." }],
    cssProperties: [
      { name: "--input-focus-outline", description: "Overrides the size-specific focus outline, including `none` for composed instances that provide another visible focus treatment." },
      { name: "--input-before-slot-max-width", description: "Maximum width for leading external slot content." },
      { name: "--input-after-slot-max-width", description: "Maximum width for trailing external slot content." },
      { name: "--input-slot-wrap", description: "Wrapping behaviour for external slot content." },
      { name: "--input-slot-overflow-x", description: "Horizontal overflow behaviour for external slot content." },
    ],
  },
};
