export const muiApi = {
  "mui-prompt": {
    description: "Provides a rich prompt composer with actions, previews, loading, and feedback states.",
    attributes: [
      { name: "placeholder", type: { text: "string" }, default: "Reply to Mui...", description: "Textarea placeholder." },
      { name: "value", type: { text: "string" }, default: "", description: "Initial prompt value." },
      {
        name: "rows",
        type: { text: "number" },
        default: "3",
        description: "Controls the growth range and cap while retaining the default prompt baseline height.",
      },
      {
        name: "enter-submit",
        type: { text: "boolean" },
        default: "true",
        description: "Submits when Enter is pressed; Shift+Enter inserts a new line.",
      },
      {
        name: "actions-fan",
        type: { text: "boolean" },
        default: "false",
        description: "Explicitly enables fan-mode actions; this is otherwise derived from slotted actions.",
      },
      { name: "fan-open", type: { text: "boolean" }, default: "false", description: "Opens fan actions by default." },
      { name: "ring", type: { text: "boolean" }, default: "false", description: "Replaces the default border with a lively animated glowing stroke ring." },
      { name: "disabled", type: { text: "boolean" }, default: "false", description: "Disables prompt input." },
      {
        name: "loading",
        type: { text: "boolean" },
        default: "false",
        description: "Displays built-in loading feedback and prevents submission while active.",
      },
      {
        name: "loading-label",
        type: { text: "string" },
        default: "Sending",
        description: "Accessible label used by the built-in loading spinner.",
      },
      {
        name: "context-mode",
        type: { text: '"icon" | "chip"' },
        default: "icon",
        description: "Controls which content inside `mui-prompt-toggle` is visible.",
      },
      {
        name: "preview-dialog-width",
        type: { text: "string" },
        default: "560px",
        description: "Width used by the internal preview dialog.",
      },
      {
        name: "preview-dialog-title",
        type: { text: "string" },
        default: "Pasted Content",
        description: "Fallback title used by the internal preview dialog.",
      },
      {
        name: "preview-dialog-bordered",
        type: { text: "boolean" },
        default: "false",
        description: "Applies `var(--border-thin)` to the internal preview dialog.",
      },
      {
        name: "--prompt-preview-dialog-border",
        type: { text: "css var" },
        default: "var(--dialog-border), or var(--border-thin) when preview-dialog-bordered is set",
        description: "Border value passed to the internal preview dialog for custom border styling.",
      },
      {
        name: "preview-overflow-to-preview",
        type: { text: "boolean" },
        default: "true",
        description: "Converts sufficiently long pasted text into preview items instead of inserting it into the textarea.",
      },
      {
        name: "preview-threshold-chars",
        type: { text: "number" },
        default: "220",
        description: "Character threshold at which pasted text becomes a preview item.",
      },
      {
        name: "preview-auto-clickable",
        type: { text: "boolean" },
        default: "true",
        description: "Automatically enables activation behaviour on slotted previews.",
      },
      {
        name: "preview-loading",
        type: { text: '"true" | "auto"' },
        description: "Applies loading state to slotted previews; `auto` mirrors the prompt loading state.",
      },
      {
        name: "preview-loading-label",
        type: { text: "string" },
        default: "Loading preview",
        description: "Accessible loading label passed to slotted previews.",
      },
      {
        name: "preview-scrollbar",
        type: { text: '"hidden"' },
        description: "Hides scrollbar chrome while retaining horizontal preview scrolling.",
      },
      {
        name: "error-message",
        type: { text: "string" },
        default: "",
        description: "Error content rendered beneath the prompt.",
      },
      {
        name: "debug",
        type: { text: "boolean" },
        default: "false",
        description: "Renders built-in status and payload output for diagnostics.",
      },
      {
        name: "effects-off",
        type: { text: "boolean" },
        default: "false",
        description: "Disables prompt hover and focus visual effects.",
      },
      {
        name: "color-top-start",
        type: { text: "string" },
        description: "Optional CSS color override for the top mesh starting color.",
      },
      {
        name: "color-top-mid",
        type: { text: "string" },
        description: "Optional CSS color override for the top mesh middle color.",
      },
      {
        name: "color-top-end",
        type: { text: "string" },
        description: "Optional CSS color override for the top mesh ending color.",
      },
      {
        name: "color-top-accent",
        type: { text: "string" },
        description: "Optional CSS color override for the top mesh accent color.",
      },
      {
        name: "color-layout",
        type: { text: '"default" | "swap"' },
        default: "default",
        description: "Selects the mapping of top mesh color positions.",
      },
      {
        name: "ring",
        type: { text: "boolean" },
        description: "Enable a glowing animated stroke variant for the prompt surface.",
      },
      {
        name: "ring-start",
        type: { text: "string" },
        description: "Overrides the start color of the glowing animated stroke.",
      },
      {
        name: "ring-mid",
        type: { text: "string" },
        description: "Overrides the middle color of the glowing animated stroke. If omitted, uses ring-start.",
      },
      {
        name: "ring-end",
        type: { text: "string" },
        description: "Overrides the end color of the glowing animated stroke. If omitted, uses ring-start.",
      },
    ],
    slots: [
      { name: "context", description: "Optional context content displayed above the prompt input, usually `mui-prompt-context`." },
      { name: "preview", description: "Preview items displayed above the prompt input, typically `mui-prompt-preview`." },
      { name: "input", description: "Optional replacement content for the built-in textarea region." },
      { name: "actions", description: "Leading prompt actions such as buttons, icons, toggles, or rules." },
      { name: "actions-right", description: "Trailing action override for the built-in submit or state action." },
    ],
    members: [
      { kind: "field", name: "value", type: { text: "string" }, description: "Gets or sets the current prompt text." },
      { kind: "field", name: "errorMessage", type: { text: "string" }, description: "Gets or sets the current error message." },
      { kind: "method", name: "submit", description: "Requests submission of the current prompt value." },
      { kind: "method", name: "clear", description: "Clears the prompt value and related visible state." },
      { kind: "method", name: "setError", description: "Sets an error message for the prompt." },
      { kind: "method", name: "clearError", description: "Clears the current prompt error message." },
      { kind: "method", name: "focus", description: "Moves focus to the prompt text input." },
    ],
    events: [
      { name: "input", description: "Dispatched when the prompt value is changed." },
      { name: "before-submit", description: "Cancelable event dispatched before submission; prevent it to block submission." },
      { name: "submit", description: "Dispatched after an accepted submit request with value and source details." },
      { name: "prompt-paste", description: "Dispatched when pasted or uploaded content is converted into prompt preview data." },
      { name: "prompt-context-change", description: "Dispatched when prompt context is changed." },
      { name: "prompt-context-dismiss", description: "Dispatched when prompt context is dismissed." },
      { name: "prompt-error-set", description: "Dispatched when an error message is set programmatically." },
      { name: "prompt-error-clear", description: "Dispatched when an existing error message is cleared." },
    ],
    cssProperties: [
      { name: "--prompt-accent-primary", description: "Primary accent used to synthesize prompt hover and focus effects." },
      { name: "--prompt-accent-secondary", description: "Optional secondary accent used in prompt hover and focus effects." },
      { name: "--prompt-preview-code-background", description: "Background passed to auto-preview `mui-code` content displayed inside Prompt." },
      { name: "--prompt-accent-primary-derived", description: "Resolved primary effect accent; can be overridden to tune prompt effects." },
      { name: "--prompt-accent-secondary-derived", description: "Resolved secondary effect accent; can be overridden to tune prompt effects." },
      { name: "--prompt-accent-mid", description: "Intermediate effect accent blended from the prompt accent colors." },
      { name: "--prompt-start-tint", description: "Start tint used in the prompt effect layers." },
      { name: "--prompt-mid-tint", description: "Middle tint used in the prompt effect layers." },
      { name: "--prompt-end-tint", description: "End tint used in the prompt effect layers." },
      { name: "--prompt-accent-tint", description: "Accent tint used in the prompt effect layers." },
      { name: "--prompt-layer-start-tint", description: "Final start tint used after color layout ordering is applied." },
      { name: "--prompt-layer-mid-tint", description: "Final middle tint used after color layout ordering is applied." },
      { name: "--prompt-layer-end-tint", description: "Final end tint used after color layout ordering is applied." },
      { name: "--prompt-layer-accent-tint", description: "Final accent tint used after color layout ordering is applied." },
      { name: "--prompt-spectrum-blend-mode-hover", description: "Blend mode applied to prompt hover effect layers." },
      { name: "--prompt-spectrum-blend-mode-focus", description: "Blend mode applied to prompt focus effect layers." },
      { name: "--prompt-ring-shadow-color", description: "Color of the drop shadow applied when the ring variant is active." },
      { name: "--prompt-ring-gap-color", description: "Color of the gap segment in the ring variant conic gradient." },
    ],
  },
};
