import type { MuiDocs } from "../../types/guidelines";

export const muiDocs: MuiDocs = {
  Prompt: {
    title: "Prompt",
    description: "Prompt provides a reusable prompt surface with floating actions and Enter-to-submit behavior.",
    hero: [""],
    figma: ["https://www.figma.com/design/l0mt1lXu97XoHJCEdnrWLp/Mui-Design-System?node-id=2117-17601&t=P2Vr2JDCBlI425XD-1"],
    storybook: ["https://stories.muibook.com/?path=/docs/ai-llm-prompt--docs"],
    github: ["https://github.com/michaeltrilford/muibook/tree/main/src/components/mui-prompt"],
    website: ["https://muibook.com/prompt"],
    guides: ["https://guides.muibook.com/prompt"],
    usage: {
      list: [
        "Use for AI/chat prompt entry surfaces with action controls.",
        "In Muibook stories, use the Interactive Prompt story at the top of the page as the primary end-to-end reference (paste/upload/context/submit).",
        "This component is extracted from composition patterns to standardize prompt behavior across experiences.",
        "Keep prompt as a controlled input in app state: write value via attribute/property and sync from input events.",
        "Use Enter submit for fast send flows; keep Shift+Enter for multiline authoring.",
        "Press Enter to submit and Shift+Enter to add a newline.",
        "Set enter-submit='false' to disable Enter submit behavior.",
        "Use slot='actions' for utility actions (attach, source, tools).",
        "Prompt includes a default submit control in actions-right; override by slotting your own actions-right control when needed.",
        "All utility actions are intended to be slotted so product teams can wire behavior from app state.",
        "A default fan trigger is included out-of-the-box for action fan behavior.",
        "Use slot='actions-right' when you need a custom submit/toggle action instead of the default.",

        "Set loading to show built-in async feedback spinner beside actions-right while requests are in flight.",
        "Use loading-label to provide accessible status text for the spinner.",
        "Fan behavior derives from slotted actions by default; use fan-open when you want the fan open by default.",
        "fan-open normalizes fan behavior in composed trees by enabling fan mode when needed.",
        "Use context-mode='icon|chip' with slotted <mui-action-toggle> for app-driven context state.",
        "Use slot='context' for explicit context content above the input, usually <mui-context-bar>.",
        "Only render slotted context when product state has real context to show.",
        "Keep feature-specific context controls inside the slotted context component; Prompt only positions the slot.",
        "Fan spread, speed, and amplitude are fixed to system defaults; tune through component tokens/CSS where needed.",
        "Built-in preview dialog handling is enabled for preview-chip-open events.",
        "Set preview-threshold-chars to control when pasted text is converted into preview attachments.",
        "Set preview-overflow-to-preview='false' to always paste text directly into the textarea.",
        "When internal preview dialog handling is enabled, slotted prompt previews are auto-clickable by default.",
        "Set preview-auto-clickable='false' to keep previews non-clickable unless explicitly configured.",
        "Set preview-loading to force slotted previews into loading state while async metadata resolves.",
        "Set preview-loading='auto' to mirror prompt loading state onto slotted previews.",
        "Use preview-loading-label to provide accessible loading text for preview spinners.",
        "Use error-message for direct prompt-level error feedback rendered below the input.",
        "Set debug to render built-in submit debug telemetry (status + JSON payload) below the prompt.",
        "Use slot='error' to render fully custom error content when product needs bespoke treatment.",
        "Use setError(message) and clearError() for app-driven validation and transport error handling.",
        "Use prompt-paste to ingest user clipboard payloads and convert them into preview-chip items.",
        "Use preview-chip-open to react to preview activation and update app-level analytics/state.",
        "For native media previews, use direct .mp4/.mp3 values so the built-in dialog opens with native media controls.",
        "Prefer system/semantic tokens for color-top-* values when theming prompt color surfaces.",
        "For React wrappers, map CustomEvent handlers to props (onSubmit, onPromptPaste, onPreviewChipOpen, onEscape).",
        "Mark the trigger action with fan-trigger; if omitted, the first action is used.",
        "Prefer this component instead of ad hoc prompt wrappers when the same interaction model is needed.",
      ],
    },
    accessibility: {
      designerList: [
        "Provide clear prompt intent through nearby heading/body context; placeholder alone should not carry all instruction.",
        "Ensure action icons are understandable and consistently positioned (utility actions left, submit/state action right).",
        "Keep status text low-emphasis visually, but persistent enough to communicate send state changes.",
      ],
      engineerList: [
        "Support keyboard parity: Enter submits, Shift+Enter adds newline.",
        "If showing send status, use an aria-live region so updates are announced to assistive tech.",
        "Do not trap focus; users must be able to tab into and out of the prompt and actions naturally.",
        "Ensure slotted context controls have their own labels and keyboard behavior.",
        "Ensure a clear placeholder or label context for prompt intent.",
        "Provide aria-label values for icon-only action buttons slotted into actions.",
        "When authoring themes, rely on public --prompt-* tokens and attributes rather than internal prompt CSS variables.",
      ],
    },
    anatomy: { image: "", list: ["Prompt surface", "Context slot", "Input area", "Action slot"] },
    variants: { items: [{ key: "", title: "", description: "", image: "" }] },
    stories: { items: [
      { key: "preview-data", title: "Interactive Prompt", description: "Canonical interactive setup for this page: paste and upload previews, context toggle, submit, and Prompt event telemetry.", list: [] },
      { key: "context", title: "Context", description: "Prompt positions explicit context content above the input when product state has context to show.", list: ["Use slot='context' for feature-owned Prompt context such as steering, persona, constraints, selected context, examples, or attachments.", "Use mui-context-bar for the compact row treatment.", "Omit the slotted context entirely when there is no active context."] },
      { key: "default", title: "Empty", list: ["Use this shared Prompt primitive across products."] },
      { key: "glowing-ring", title: "Glowing Ring", description: "Enable ring for an animated glowing stroke. Use ring-start, ring-mid, and ring-end to define the color sweep.", list: [] },
      { key: "submit-guard-api", title: "Submit Guard + API", description: "Use before-submit to block invalid sends, then call submit, clear, or focus from application controls.", list: [] },
      { key: "loading", title: "Async Loading", description: "Show async spinner feedback next to submit while a request is in flight.", list: [] },
      { key: "preview-loading-flow", title: "Preview Loading Flow", description: "Working async flow that toggles preview loading from an LLM or tooling lifecycle.", list: ["Set Prompt loading during the request and mirror preview loading using preview-loading='auto'.", "If enrichment continues after send completes, force preview-loading='true' and clear it when finished."] },
      { key: "error-feedback", title: "Error Feedback", description: "Inject direct error text or custom slot content. Long errors can expand for review.", list: ["Use Bad Data for raw machine or system validation output.", "Use Custom Data for humanised guidance.", "Use Reset to clear both direct error-message and custom slotted error content."] },
      { key: "effects-off", title: "Effects Off", description: "Disable Prompt hover and focus visuals for a flatter surface.", list: [] },
      { key: "color-swap", title: "Color Layout Swap", description: "Remap the top color positions without changing the supplied color values.", list: [] },
      { key: "preview-open-image-dialog", title: "Preview: Image", description: "Click an image preview to open the built-in Prompt dialog.", list: [] },
      { key: "preview-media", title: "Preview: Media", description: "Checks media badges and rendering for YouTube, SoundCloud, and direct media URLs.", list: ["Use Interactive Prompt for the complete paste and upload flow."] },
      { key: "preview-native-video", title: "Preview: Native Video", description: "Uses a direct MP4 URL so the dialog opens with native video controls.", list: [] },
      { key: "preview-native-audio", title: "Preview: Native Audio", description: "Uses a direct MP3 URL so the dialog opens with native audio controls.", list: [] },
      { key: "preview-open-dialog", title: "Preview: Code Types", description: "Formats JSON and CSS in the built-in dialog while other types render source content for comparison.", list: [] },
      { key: "preview-off", title: "Preview: Off", description: "Disable preview auto-click so items remain non-interactive.", list: [] },
    ] },
    compositions: { description: "", items: [] },
    related: {
      items: [
        { name: "Input", link: "https://guides.muibook.com/input" },
        { name: "Button", link: "https://guides.muibook.com/button" },
      ],
    },
    rules: [
      {
        heading: "Pattern Rule",
        description: "Use Prompt as the shared prompt-surface primitive; keep product-specific flows in compositions.",
        doContent: [
          { description: "Reuse this component when Enter submit + floating actions are expected.", image: "" },
        ],
        dontContent: [
          { description: "Do not rebuild the prompt shell in each composition with custom wrappers.", image: "" },
        ],
      },
    ],
    behaviour: {
      list: [
        "Enter emits a submit event with current value.",
        "Shift+Enter inserts a newline.",
        "Pasting emits prompt-paste with detected payload metadata for consumers to store and render previews.",
        "Short text paste remains in the textarea; long text and binary paste can be converted to preview items based on threshold settings.",
        "Clicking a preview emits preview-chip-open with normalized preview payload (badge, value, image metadata).",
        "Escape emits escape and closes fan actions when open.",
        "Error feedback supports dismiss and optional expand/collapse for long copy.",
        "Clicking content inside a slotted <mui-action-toggle> emits prompt-context-change and switches to context chip mode.",
        "Dismissing content marked with [context-chip] emits prompt-context-dismiss and returns to icon mode.",
        "Slotted context content appears above the prompt input when provided by the consumer.",
        "Actions remain anchored at the prompt edge while text grows.",
        "Action behavior should be equivalent whether triggered by keyboard submit or click.",
        "When loading is set, prompt shows async spinner feedback near submit and blocks additional submits.",
      ],
    },
    writing: {
      list: ["Use clear placeholder prompts that describe expected user input."],
    },
  },
};
