import type { MuiDocs } from "../../types/guidelines";

export const muiDocs: MuiDocs = {
  Menu: {
    title: "Menu",
    description: "Menu provides a reusable visual surface for dropdown and anchored overlay content.",
    hero: [""],
    figma: [""],
    storybook: [""],
    github: ["https://github.com/michaeltrilford/muibook/blob/main/src/components/mui-menu/index.ts"],
    website: ["https://muibook.com/menu"],
    guides: [""],
    usage: { list: ["Use inside mui-dropdown to compose the portalled menu surface.", "Use size='x-small|small|medium|large' to scale the surface radius and all direct button or link actions together.", "Render independently when reviewing menu layouts and grouped overlay content."] },
    accessibility: { designerList: ["Keep menu actions concise and easy to scan."], engineerList: ["Use Dropdown when trigger, focus, dismissal, and positioning behaviour is required."] },
    anatomy: { image: "", list: ["Surface", "Menu content"] },
    variants: { items: [] },
    stories: {
      items: [
        { key: "action-menu", title: "Action Menu", list: ["Use Menu to provide the visual surface and vertical layout for a related set of actions.", "Menu accepts direct Button or Link actions and remains fully composable with system components and their slots.", "Compose Menu inside Dropdown when the surface needs trigger, portal, positioning, focus, and dismissal behaviour."] },
        { key: "submenu", title: "Submenu", description: "Provides a viewport-aware nested Menu from a parent Menu action.", list: ["Use a direct Button as the Submenu trigger because opening nested actions is disclosure behavior, not navigation or selection.", "Hover the trigger or move keyboard focus into the Submenu to reveal its Menu.", "Submenu flips sides when space is constrained and may overlap the parent Menu as a final fallback instead of clipping outside the viewport.", "Use a top-slotted Search Input on the parent Menu when its top-level actions benefit from filtering.", "The examples cover every Menu size with the Submenu shown in first, middle, and last positions."] },
        { key: "searchable-menu", title: "Searchable Menu", list: ["Place search and filtering controls before a scrollable action set when menus contain many options.", "Keep filtering in application state; Menu provides the visual surface and composition boundary.", "Use a hidden Body with role=status and aria-live=polite for the empty-state message. Reveal it only when every searchable action is hidden."] },
        { key: "inset", title: "Inset Content", list: ["Use the inset attribute to add padding to the menu's scrollable region, allowing buttons and other nested items to retain their natural border radius instead of spanning edge-to-edge."] },
        { key: "sections", title: "Sections", list: ["Use labelled sections when one Menu contains distinct groups of related files or actions.", "Place Search before the section headings when it filters content across the complete Menu.", "Use File Icon for file-type recognition and standard system icons for destinations or commands; both inherit sizing from the containing Button."] },
        { key: "select-menu", title: "Select Menu", list: ["Use a direct Select when the chosen option establishes the context for the actions below it.", "This example selects a design-system theme before previewing, editing, duplicating, or exporting that theme.", "Set size on Menu only; Menu enforces the same size and inset treatment on the Select and direct actions."] },
        { key: "date-menu", title: "Date Menu", list: ["Use a bottom-slotted Date Picker when the selected date applies to the actions grouped above it.", "This example supports reviewing the day, creating an event, copying the date, or exporting its schedule.", "Menu propagates its size and inset field radius to the Date Picker and its composed calendar action."] },
        { key: "input-menu", title: "Input Menu", list: ["Use a bottom-slotted Input when actions above provide context for the value being entered.", "Set size on Menu only; Menu keeps the Input and actions aligned while inset preserves their individual radii."] },
        { key: "time-menu", title: "Time Menu", list: ["Use a bottom-slotted Time Picker when the selected time applies to the actions grouped above it.", "The examples cover every Menu size and inherit the same size in the composed Time Picker input."] },
        { key: "chip-input-menu", title: "Chip Input Menu", list: ["Use a top-slotted Chip Input to filter or assign multiple values before acting on the selection.", "The examples cover every Menu size and keep the selected chips seamless with the Menu surface."] },
        { key: "language-toggles", title: "Language Toggles", list: ["Use composed rows for independent settings rather than menu commands.", "File Icon adds fast language recognition while Switch owns each boolean selection."] },
        { key: "range-input-menu", title: "Range Input Menu", list: ["Use Range Input for an adjustable value within a compact settings or playback menu.", "Nested controls are sized explicitly from the same Menu size because only direct Menu children inherit size automatically."] },
        { key: "sizes", title: "Sizes", list: ["Menu supports x-small, small, medium, and large.", "The selected size controls the surface radius and is enforced on direct button and link actions."] },
        { key: "grouped-content", title: "Grouped Content", list: ["Use concise headings and rules to separate related groups without turning the menu into a full page layout.", "Menu accepts composed content, but interactive actions should remain easy to scan and operate.", "Use inset when grouped actions should retain their individual radii and sit inside the Menu edge."] },
        { key: "selectable-actions", title: "Selectable Actions", description: "Adds application-owned single-selection behavior to a composed Menu.", list: ["Menu does not select actions automatically; manage the selected value and visual treatment in application state.", "Use the primary treatment only when an action represents the current selection, not for ordinary commands or Submenu triggers.", "Update aria-pressed with the visual variant so assistive technology receives the same selected state.", "The active appearance shown here is the base theme treatment; customize it to suit your product theme.", "Disable an action only when it must remain visible but cannot currently be used."] },
      ],
    },
    compositions: { description: "", items: [] },
    related: { items: [{ name: "Dropdown", link: "https://guides.muibook.com/dropdown" }] },
    rules: [],
    behaviour: { list: ["Menu owns presentation only; Dropdown owns overlay interaction and portal behaviour.", "Menu enforces its size and align='start' on direct Button and Link children while leaving rules and custom grouped content independently composed.", "A direct Submenu passes the same Menu action context to its direct Button trigger.", "Menu radius is capped by the matching form radius so circular action tokens cannot turn the surface into a pill.", "Direct Body content receives action padding so headings and labels align with Menu actions.", "Top and bottom slots provide compositional regions, apply seamless form-control surfaces, and add a separator only when populated.", "Use inset when a Menu includes top or bottom content; keep action-only menus edge-to-edge.", "Inset state is passed to direct Button and Link actions so each component applies its own size-specific action padding independently from Menu content padding.", "When a direct Body heading precedes the first action, that action remains square at the top because the heading already buffers it from the Menu edge."] },
    writing: { list: ["Use short action labels and group related commands together."] },
  },
};
